name: gof
channels:
  - pytorch
  - nvidia/label/cuda-11.6.2
  - conda-forge
  - defaults
dependencies:
  - cmake
  - cgal
  - cuda-toolkit=11.6
  - gmp
  - gputil=1.4.0
  - gcc=9.5
  - gxx=9.5
  - lpips=0.1.4
  - ninja
  - numpy=1.23.5
  - pillow=9.4.0
  - plyfile=1.1
  - python=3.9
  - pip=22.3.1
  - pytorch=1.12.1
  - pytorch-cuda=11.6
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - trimesh=4.6.3
  - pip:
    - einops==0.8.1
    - open3d==0.19.0
    - scikit-image==0.24.0
    - tensorboard==2.19
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
